### ISSUE TITLE
Some y axis labels are turning into exponencial notations

### ISSUE THREAD

**Issue by glha** [igorecarrasco/covidbot#7]
Bellow graph is an example of it. The numbers are not big, but they are showing 2x10² instead of 200, then 250 normally, again 3x10², 4x10², here it is a normal 500, then 6x10²...

![image](https://user-images.githubusercontent.com/11889385/80172075-5e45be00-85c2-11ea-9bff-7bf008368830.png)

[https://twitter.com/COVID19_bot/status/1253524085822222336](https://twitter.com/COVID19_bot/status/1253524085822222336)

**Comment by igorecarrasco** [comment]
This has been fixed!
